content/posts/articles/2020/08/mobx-study-4.md
=> [Post] MobX 10분 요약 글 완성

content/posts/articles/2020/09/javascript-string.md
=> [Post] Javascript String

config.js
- 노션으로 링크되는 신규 메뉴 추가
- 메뉴명 변경
- `Articles` > 'Posts'
=> [Feature] 신규 메뉴 추가

content/posts/articles/2020/07/github-actions-summary.md, content/posts/articles/2020/07/make-use-of-long-term-caching.md, content/posts/articles/2020/07/memory-leaks-in-javascript.md, content/posts/articles/2020/09/javascript-memory-leaks-by-window-detached.md
- [Post] Javascript Memory Leak by Detached Window
- fix typo
=> [Post] Javascript Memory Leak by Detached Window

pages/tag/[tag]/page/[id].tsx, pages/tags.tsx, src/utils/frontMatters.ts
=> 태그 목록 페이지 구성

pages/about.tsx, pages/contacts.tsx, src/config.ts
this closes #99 
this closes #100
=>  about & contact

pages/[year]/[month]/[day]/[title].tsx, pages/[year]/[month]/[day]/index.tsx, pages/about.tsx, pages/contacts.tsx, pages/index.tsx, pages/page/[id].tsx, pages/tag/[tag]/page/[id].tsx, pages/tags.tsx, src/components/Layout.tsx
=> 공유를 위한 OG TAG 설정

package-lock.json, package.json, src/utils/Markdown.ts
=> [#118] autolink

README.md, content/posts/articles/2018/07/03/ethereum-create-private-blockchain-2.md, content/posts/articles/2019/02/13/pytorch-fashion-MNIST.md, content/posts/articles/2019/02/15/pytorch-flower-classification.md, content/posts/articles/2019/02/19/pytorch-02-linear-regression.md, content/posts/articles/2020/10/IIFE-on-use-state-of-react.md
=> [Post] #104

package-lock.json, package.json, src/components/Post/Post.tsx
=> [#105] icons in post

content/posts/articles/2020/10/react-hooks-and-hocs.md, src/utils/Markdown.ts, tsconfig.node.json, types/mapbox__rehype-prism.d.ts, types/remark-slug.d.ts
=> [#104] React hooks vs HOC

pages/index.tsx
=> [Optimization] 라이트 하우스 점수 향상을 위한 시도

.github/workflows/algolia.yaml, package-lock.json, package.json, src/algolia.ts
- algolia에 데이터 업로드하는 코드 추가
- master 에 push 시 자동으로 데이터 업로드
=> Algolia 작업 추가

content/posts/articles/2020/11/test-eslint-config.md
=> [#155] eslint-config 테스트 코드 작성

.editorconfig, .eslintrc.js, pages/[year]/[month]/[day]/[title].tsx, pages/[year]/[month]/[day]/index.tsx, pages/about.tsx, pages/contacts.tsx, pages/index.tsx, pages/page/[id].tsx, pages/tag/[tag]/page/[id].tsx, pages/tags.tsx, src/components/Feed.tsx, src/components/Layout.tsx, src/components/Post/Post.tsx, src/components/Post/components/Author.tsx, src/components/Sidebar/Author.tsx, tsconfig.json
=> Module Alias 적용

content/posts/articles/2018/07/03/ethereum-create-private-blockchain-1.md, content/posts/articles/2019/02/25/pytorch-08-CIFAR-10.md
=> [Fix] 사용성 이슈 해결

src/utils/Markdown.ts
=> [Fix] 타임존 문제 해결

posts/2020/12/typescript-performance-tip.md
=> [Post] initial commit

pages/_document.tsx
=> 🔥  add Firebase script

posts/2019/02/19/pytorch-01-tensor.md, posts/2019/02/19/pytorch-02-linear-regression.md, posts/2019/02/19/pytorch-03-perceptron.md, posts/2019/02/20/pytorch-04-deep-neural-network.md, posts/2019/02/21/pytorch-05-image-recognition.md, posts/2019/02/21/pytorch-06-convolutional-neural-network(1).md, posts/2019/02/21/pytorch-07-convolutional-neural-network(2).md, posts/2019/02/25/pytorch-08-CIFAR-10.md
=> [Fix] add python tag

pages/api/screenshot.ts
- Cloudinary Secret 제거
-  puppeteer 세팅 변경
=> [#213] add settings

posts/2021/01/nextjs-refresh-server-side-props.md
=> [Post] #240 nextjs refresh serverside props

public/ads.txt
=> ads.txt 추가

package-lock.json, package.json, pages/_app.tsx
- 패키지 버전업
- `_app` 내부의 `getInitialProps` 삭제
=> [Blog] 패키지 버전업

posts/2021/03/improve-css-performance.md
=> [Post] improve-css-performance

.eslintignore, .github/workflows/ci.yaml, .github/workflows/lighthouse-ci.yaml, .gitignore, .prettierignore, lighthouserc.js
=> [Feature] lighthouseci 추가

pages/404.tsx, pages/_app.tsx, pages/_document.tsx, pages/_offline.tsx
- https://www.filamentgroup.com/lab/load-css-simpler/
- https://d2.naver.com/helloworld/4969726
=> Lazy load css

.github/workflows/lint.yaml, .husky/pre-commit, package-lock.json, package.json, posts/2021/05/ast-for-javascript.md, public/2021/05/images/flowchart.svg
- this closes #165
- lint와 build 병렬로 실행되도록 변경
- husky 버전업
=> [Post] Abstract Syntax Tree

src/config.ts
github link 를 수정합니다
무엇을 좋아하시는지몰라 입맛대로했습니다 ..
=> github link 를 수정합니다

posts/2021/06/misconceptions-on-nodejs.md
=> [Post] misconceptions of nodejs

posts/2021/06/error-handling-in-nodejs.md
=> [Post] Error Management in Node.js Applications

pages/_app.tsx, pages/_document.tsx, src/components/layouts/Post.tsx, src/components/layouts/Post/math.tsx
Nextjs 팀의 권고에 따라
- script를 _document.tsx에서 _app.tsx로 이동
- katex 스크립트를 post에서 불러오도록 변경
=> [Blog] 최적화

posts/2021/06/reduce-spread-anti-pattern.md
=> [Post] Reduce Spread Operator

public/robots.txt, src/pages/[year]/[...slugs].tsx, src/pages/tags/[tag]/pages/[id].tsx, tsconfig.json
=> [Blog] sitemap 개선작업

package-lock.json, package.json, posts/2021/07/dont-use-nodjs-orm.md
=> Nodejs ORM

posts/2018/09/19/how-does-proof-of-authority-consensus-work.md, posts/2021/07/kill-a-nodejs-process.md, posts/2021/07/nodejs-modules-packages-semver.md
=> [Post] Death of Nodejs process

functions/index.js, functions/package-lock.json, functions/package.json, functions/ui-debug.log, src/pages/generate-screenshot.tsx, src/utils/common.ts
this closes #378
- pupeteer로 이제 직접 스크린샷 촬영
- 리전 변경으로 개선된 속도
=> [Blog] og:img 공사

posts/2021/08/browser-nodejs-event-loop.md, tailwind.config.js
=> [Post] Browser & nodejs Event loop

next-env.d.ts, next.config.js, package-lock.json, package.json
=> [Blog] Nextjs 11

posts/2021/08/requestIdlecallback.md
=> [Post] Fix Typo

posts/2021/08/uncaught-async-error.md
=> [Post] uncaught async error

next-env.d.ts, posts/2021/09/javascript-random-number.md
=> [Post] generate Random Number in javascript

posts/2021/08/benchmarking-web-javascript-memory-usage.md, posts/2021/09/memoize-async-function.md
this closes #413 
cc) @kyujonglee
=> [#413] fix wrong argument

next-env.d.ts, posts/2021/09/deep-dive-javascript-regex.md, posts/2021/09/javascript-random-number.md
=> [Post] Javascript Regex

posts/2021/09/github-ci-workflow-for-frontend-developer.md
=> [Post] github CI workflow

posts/2021/10/get-absolute-url-in-nextjs.md
=> [Post] get absolute URL in nextjs

posts/2021/11/responsibility-of-javascript-code-2.md, posts/2021/11/responsibility-of-javascript-code.md
=> [Post] Responsibility of javascript

src/common/types.ts, src/utils/Post.ts
_Disable JavaScript_
---
_Enable JavaScript_
#153
```js
// before
const date = '2022-01-17T08:09:50.000Z';
// after
const date = '2022-01-17T08:09:50';
```
=> [Fix] fix date mismatch in post

posts/2022/02/rust-for-javascript-developer-chapter1.md, posts/2022/03/rust-for-javascript-developer-chapter2.md
=> [Rust] string

posts/2022/03/polymorphic-function-in-typescript.md
=> [Post] typescript의 다형성

posts/2022/03/polymorphic-function-in-typescript.md, posts/2022/03/typescript-omit-exclude-pick.md
=> [Post] Typescript Omit

posts/2022/04/react-18-changelog.md
=> [Post] React 18 CHANGELOG

package-lock.json, package.json, posts/2022/04/react-18-changelog.md, src/tailwind.css, src/utils/Markdown.ts
=> [Blog] 새로운 code-highlight 도입

Dockerfile, k8s/app/deployment.yaml, k8s/app/ingress.yaml, k8s/app/service.yaml, package-lock.json, package.json
- http://34.111.188.163/
- 아니 근데 이렇게 하면 CI/CD를 다 구축해야할거같은데 현기증나네
=> [K8S] gcp로 앱 설정해보기

posts/2022/05/typescript-tips-and-tricks.md
=> [Post] typescript tips and tricks

posts/2022/05/how-typescript-compiler-works.md, posts/2022/06/how-to-write-my-own-eslint-rules.md
=> [Post] 나만의 eslint 룰 만들어보기

.github/workflows/lighthouse.yaml, lighthouserc.js, package.json, pnpm-lock.yaml, src/app/layout.tsx
- https://github.com/GoogleChrome/lighthouse-ci/issues/799
- 왠지 관리가 잘 안되는 듣한 느낌
=> 🛠️  라이트 하우스 이슈 수정
